# .github/workflows/vercel-production.yml

name: Vercel-Production Deploy

on:
  push:   # triggers Vercel-Production Deploy on push to main branch
jobs:
  vercelproductiondeploy:
    runs-on: ubuntu-latest
    # IMPORTANT: the workflow must have write access to deployments, otherwise the action will fail.
    permissions:
      deployments: write
    
    steps:
      # 1. Clone the repo into the GitHub Actions runner
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.event.push.head.sha }}

      # 2. Install correct Node version
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      # 3. Deploy to Vercel Production
      - name: Deploy to Vercel Production
        id: vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
          github-comment: true

      # 4. Create GitHub deployment (vercel-production)
      - name: Create GitHub deployment (vercel-production)
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.vercel.outputs.preview-url }}
          environment: vercel-production

      # 5. Update GitHub deployment status for Vercel
      - name: Update GitHub deployment (Vercel)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.vercel.outputs.preview-url }}
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          description: "Deployed to Vercel"